name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: bash -l {0}
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: |
          nvm use lts/hydrogen
          npm install
          npm run all

      - uses: ./
        with:
          root: test
          extraFiles: test/foo.sh # for the ammonite-runner version

      - run: cd test && ./sbt compile && ./foo.sh
        shell: bash
