name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        shell: bash -l {0}
        run: |
          nvm use lts/gallium
          npm install
          npm run all

      - uses: ./
        with:
          root: test
          extraFiles: test/foo.sh # for the ammonite-runner version

      - run: cd test && ./sbt compile && ./foo.sh
        shell: bash
