name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Build
        shell: bash -l {0}
        run: |
          npm ci
          test "$OSTYPE" != "msys" || npm run format
          npm run all

      - uses: ./
        with:
          root: test
          extraFiles: test/foo.sh # for the ammonite version?

      - run: cd test && eval "$(./cs java --env --jvm 17)" && ./mill -i __.compile && ./foo.sh
        if: runner.os != 'Windows'
        shell: bash

      - run: cd test && eval "$(./cs java --env --jvm 17)" && cmd /c "mill.bat -i __.compile" && ./foo.sh
        if: runner.os == 'Windows'
        shell: bash
